const srartist = {
  info: [
    {
      id: 1,
      name: 'AMEMALIA',
      description: "Amamelia is the musical project of Amelia Berry, a musician and songwriter currently based in Auckland. Her music combines breaks normally found in Jungle & Drum & Bass with a sugary synthetic pop sensibility. Throughout 2020 Amamelia has been teasing her audience with So Good and Sad and Lonely feat Junny, two singles from her debut album WOW! (due out before the years end via Sunreturn).Outside of Amamelia, Amelia can be found creating ambient soundscapes in caves as Old Chips, playing in queerbo pop-punk band Babyteeth and performing as one half of synth pop duo Fimo. In the past she's been the mastermind behind the romantic jangle of Polyester (fka as Kip McGrath), and one third of queer DJ trio PWB . She is currently host of 95bFM's illustrious chart show, the 95bFM Top 10.",
      image: 'public/Amamelia - Photo Credit Karin Yamasaki.jpeg',
      credit: "Karin Yamasaki",
      bandcamp: "https://amamelia.bandcamp.com/",
      spotify: "https://open.spotify.com/artist/7BjYtpKbFrgy8EX8REsjhW?si=qfA3AMyORyOFZtLhJCBF8Q",
      youtube: "https://www.youtube.com/playlist?list=PL3_-29X9BmxMRTNKOtqG15P4TYhHzj9ed",
      instagram: "",
      facebook: "https://www.facebook.com/amamelianz/",
    },
    {
      id: 2,
      name: 'BABY ZIONOV',
      description: "Amamelia is the musical project of Amelia Berry, a musician and songwriter currently based in Auckland. Her music combines breaks normally found in Jungle & Drum & Bass with a sugary synthetic pop sensibility. Throughout 2020 Amamelia has been teasing her audience with So Good and Sad and Lonely feat Junny, two singles from her debut album WOW! (due out before the years end via Sunreturn).Outside of Amamelia, Amelia can be found creating ambient soundscapes in caves as Old Chips, playing in queerbo pop-punk band Babyteeth and performing as one half of synth pop duo Fimo. In the past she's been the mastermind behind the romantic jangle of Polyester (fka as Kip McGrath), and one third of queer DJ trio PWB . She is currently host of 95bFM's illustrious chart show, the 95bFM Top 10.",
      image: 'a',
      credit: "Frances Carter",
      bandcamp: "https://babyzionov.bandcamp.com/",
      spotify: "https://open.spotify.com/artist/4RLTd4Vi9dfNeEKMnmylaO?si=lOx41DDJTveJZJeZhcgCKw",
      youtube: "https://www.youtube.com/playlist?list=PL3_-29X9BmxOkkdFlPFN3P6jo8ufz8cKs",
      instagram: "https://www.instagram.com/babyzionov/",
      facebook: "https://www.facebook.com/babyzionov/",
    },
    {
      id: 3,
      name: 'DATELINE',
      description: "Dateline is the musical project of Katie Everingham, a musician and songwriter currently based in Hastings. Her band is made up of the cream of Auckland's indie and alternative crop featuring Callum Devlin (Hans Pucket), Priya Sami (fka Trip Pony, Sami Sisters) and Ruby Walsh (Lips, Trip Pony). Earlier in the year Dateline supported US artist Jaysom and their scorching set was recorded and released as Dateline Live! The EP comes off the back of two hot singles, If You Want It and Such A Bitch. Those songs were recorded by Dateline's original band members Elizabeth Stokes (The Beths) Robert Bruce (The Naenae Express) and Ruby Walsh (Trip Pony). Before the year is over Dateline will hit the studio for another round of recording!",
      image: 'a',
      credit: "Mason Fairey",
      bandcamp: "https://dateline.bandcamp.com/",
      spotify: "https://open.spotify.com/artist/1qmkqOcRV8vy61b2zBBeFm?si=Sr__jEuaRUKHrqucvz5zJw",
      youtube: "https://www.youtube.com/playlist?list=PL3_-29X9BmxO3X_bFj3-XzC9QDWkH3bF_",
      instagram: "https://www.instagram.com/dateline2.0/",
      facebook: "https://www.facebook.com/Dateline2.0/",
    },
    {
      id: 4,
      name: 'GREEN GROVE',
      description: "Green Grove is the musical project of Durham Fenwick, a musician and songwriter currently based in Auckland. Green Grove's music is for deep listening, creating lush electronic worlds inspired by Lounge and Library Music. Durham has wholeheartedly immersed himself into Auckland's independent music scene, initially as the guitarist of New Gum Sarn, and then swiftly into groups such as Guardian Singles, Bozo, PG/VG and as a live sound engineer at Whammy Bar. Following the release of 2019's Machine Music, Green Grove has pivoted to a contemplative sound palette, with his live set embodying mindful ambience and graceful soundscapes.",
      image: 'a',
      credit: "Mason Fairey",
      bandcamp: "https://greengrove.bandcamp.com/",
      spotify: "https://open.spotify.com/artist/4Or9cUnJdgeT8tQ0SP7PrV?si=76-IAgTjQlqqHJBBwt9KXw",
      youtube: "https://www.youtube.com/playlist?list=PL3_-29X9BmxOJviy25j6hwBNpTIhU7Un_",
      instagram: "https://www.instagram.com/darimfennick/",
      facebook: "https://www.facebook.com/Greengrov3/",
    },
    {
      id: 5,
      name: 'K M T P',
      description: "K M T P is the musical project of Keria Paterson, a musician and songwriter currently based in Auckland. Keria  didn’t discover music at a particular point in their life, it was always there, whether it was attending Flying Nun gigs with family as a kid and starting to sing and play guitar and piano at an early age. At high school, they connected with other passionate musicians and added bass and keyboards/synths to his repertoire, as well as beginning to experiment with recording and live music production. Before starting their own solo projects as K M T P, Paterson played with Auckland indie faves Polyester, as well as with Ethan Moore’s “bedroom stadium pop” project Dirty Pixels.",
      image: 'a',
      credit: "Karin Yamasaki",
      bandcamp: "https://kmtp.bandcamp.com/album/p-s-c-u-soon",
      spotify: "https://open.spotify.com/artist/3PW65WLXS6nvUaNquvoXvO?si=DRYvU2R6Q-KKQxCwOGdTRA",
      youtube: "https://www.youtube.com/playlist?list=PL3_-29X9BmxPHHVcoX1ichAnwOBCIk-uk",
      instagram: "https://www.instagram.com/kmtpmakesmusic/",
      facebook: "https://www.facebook.com/kmtpmakesmusic/",
    },
  ]
}